export const INSERT_TODO = 'INSERT_TODO';

export const CHANGE_TODO_STATUS = 'CHANGE_TODO_STATUS';

export const ALL_TODO_COMPLETE = 'ALL_TODO_COMPLETE';

export const SETTING_SEARCH_KEY = 'SETTING_SEARCH_KEY';
